version: '3'
services:
    php:
        container_name: php
        build:
            context: ./php
        ports:
            - '9000:9000'
        volumes:
            - ./app:/var/www/symfony_calculator
    nginx:
        container_name: nginx
        image: nginx:stable-alpine
        ports:
            - '8080:80'
        volumes:
            - ./app:/var/www/symfony_calculator
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php